### ISSUE TITLE
Enable GitHub discussions and/or add Gitter to this project

### ISSUE THREAD

**Issue by JonasCir** [hzi-braunschweig/SORMAS-Angular#15]
### Current situation
There is not an easy way for the community to interact with the project's developers.

### Proposed solution
Enable GitHub discussions and/or add Gitter to this project as we do for the main project.

**Comment by alexandrudanpop** [comment]
Great idea @JonasCir!

I enabled GH discussions. The thing is right now at some point we will migrate this repo and place the code inside the Sormas-Project repo - so we will probably use the discussion channel provided there!

**Comment by JonasCir** [comment]
@alexandrudanpop Thanks :) Ok great, then everything is in one place :)
