### ISSUE TITLE
CORS proxy or setup CORS headers for SORMAS-REST

### ISSUE THREAD

**Issue by alexandrudanpop** [hzi-braunschweig/SORMAS-Angular#17]
## Current issue
For local development, I fixed this using a local Proxy, but for calling the API when running the solution with `docker-compose` we still have this:
![GH issue](https://user-images.githubusercontent.com/15979292/105179669-450e7580-5b32-11eb-9160-abacd62a9aed.png)

## Posible solutions
We can fix this eighter by proxy-ing the calls from Nginx  to the Sormas API - then the CORS check is not done server-side, or fix it by adding the proper CORS headers for the API.

**Comment by horiadev** [comment]
**Work done:**
* enabled CORS for everything on the local dev enviroment
    * this is not an issue as we are binding the ports on the local machine only, so they can only be accessed from the localhost.
* pull request is [here](https://github.com/hzi-braunschweig/SORMAS-Angular/pull/19)
