### ISSUE TITLE
Local dev setup using  SORMAS-Docker

### ISSUE THREAD

**Issue by alexandrudanpop** [hzi-braunschweig/SORMAS-Angular#9]
## Background
We need a fast way of setting a local environment for the Sormas-Project. 
We want to see if using the Sormas-Docker repository can help us with this.

## Outcome
We want to investigate and document how we can use the Sormas-Docker repo to start a local Sormas environment with:
- Sormas BE (API)
- Sormas Keyclaok 
- PostgreSQL DB
- (other containers that are needed)
https://github.com/hzi-braunschweig/SORMAS-Docker

**Comment by JonasCir** [comment]
Hi,
I'm excited to see this project!
 I already did this for SORMAS-datagen and [SORMAS-Stats](https://github.com/hzi-braunschweig/SORMAS-Stats/blob/development/docker-compose.yml) + [.env file](https://github.com/hzi-braunschweig/SORMAS-Stats/blob/development/.env)
You could take this as a reference. It already maps the ports correctly and provides a docker volume in the repo root folder (such that you could remove it quickly in case you want a fresh system:) )

Please note that these two files are behind SORMAS-Docker as I did not bump the version in a while.

**Comment by horiadev** [comment]
**Work done:**
* created a new docker-compose.yml based on the [SORMAS-Docker](https://github.com/hzi-braunschweig/SORMAS-Docker/) repository.
* added the certificates and `.env` file from it. Removed memory and CPU allocations as this is intended for local environments only.
* updated the `nginx.conf` file to have correct redirects to the default language when using custom ports
* pull request is [here](https://github.com/hzi-braunschweig/SORMAS-Angular/pull/12)
